# Generated by Django 5.2.3 on 2025-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri_klientit', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('ora_fillimit', models.TimeField()),
                ('koment', models.TextField(blank=True)),
            ],
        ),
    ]
